### ISSUE TITLE
Multi-field query crash: any find_one()-backed field errors when combined with a sibling top-level field

### ISSUE THREAD

**Issue by evoludigit** [fraiseql/fraiseql-python#448]
## Summary

Any `find_one(info=...)`-backed query field crashes with `'dict' object has no attribute
'bytes'` when the client requests it alongside **any other top-level field** in the same
GraphQL request. Confirmed on two completely unrelated resolvers in our app (one backed
by a `tv_*`-style materialized view with a dual typed-column/jsonb shape, one a plain
single-object lookup with neither property), so this doesn't look specific to any one
resolver's table shape — it looks like a general multi-field query execution bug.
`fraiseql==1.23.11` (latest available 1.x LTS patch as of this report — no newer 1.23.x
on PyPI).

## Reproduction

```graphql
# ❌ crashes
{ someObjectField { someScalar } someUnrelatedField }

# ✅ works
{ someObjectField { someScalar } }
```

Concretely, in our schema:

```graphql
# ❌ "'dict' object has no attribute 'bytes'"
{ machineInventoryStatistics { nMachine } machinesCount }

# ❌ same error, different resolver entirely (no tv_* table, no jsonb dual-shape)
{ me { role } machinesCount }

# ✅ either field alone works fine, with any sub-field selection
{ machineInventoryStatistics { nMachine nCurrent nAllocated nStock nUnallocated nDecommissioned } }
{ me { id role } }
```

Full error:

```json
{
  "data": {"machineInventoryStatistics": null, "machinesCount": 284},
  "errors": [{"message": "'dict' object has no attribute 'bytes'", "path": ["machineInventoryStatistics"]}]
}
```

Server-side log (with the resolver's own `info=` kwarg omitted — see below for why that
doesn't help):

```
ERROR fraiseql.fastapi.routers: Failed to execute resolver for field 'machineInventoryStatistics': 'dict' object has no attribute 'bytes'
ERROR fraiseql.fastapi.routers: Multi-field query execution failed
Traceback (most recent call last):
  File ".../fraiseql/fastapi/routers.py", line 1503, in graphql_endpoint
    result = await execute_multi_field_query(schema, request.query, request.variables, context)
  File ".../fraiseql/fastapi/routers.py", line 1038, in execute_multi_field_query
    response_bytes = fraiseql_rs.build_multi_field_response(field_data_list)
  File ".../fraiseql/core/rust_pipeline.py", line 90, in build_multi_field_response
    return _FraiseQLRs._module.build_multi_field_response(*args, **kwargs)
TypeError: 'int' object is not an instance of 'str'
while processing 'fields'
WARNING fraiseql.fastapi.routers: Falling back to standard graphql-core execution
```

So there appear to be two layered bugs:
1. `fraiseql_rs.build_multi_field_response` (Rust) raises `TypeError: 'int' object is not
   an instance of 'str' while processing 'fields'` when asked to merge results for two
   top-level fields of different kinds (at minimum, an object-returning field alongside a
   scalar-returning one — we also reproduced it with two object-returning fields, so it
   may not be scalar-specific).
2. On that failure, FraiseQL falls back to standard graphql-core execution — and *that*
   fallback path is what then hits the `'dict' object has no attribute 'bytes'` crash
   (psycopg's `UUIDDumper` apparently receiving a dict as a bound query parameter) inside
   `find_one`'s selection-aware projection logic.

## Why omitting `info=` at the resolver call site does not help

We tried the obvious fix — stop passing `info=info` to `db.find_one(...)` in our
resolver, since the projection narrowing isn't needed for a single-row-per-tenant table
anyway. This fixes the *single-field* case (any field selection, with or without an `id`
field, all work) but has **no effect** on the multi-field case, because:

- `fraiseql.middleware.graphql_info_injector` writes `info` onto
  `db.context["graphql_info"]` before every resolver runs.
- `db.find_one()` (`fraiseql/db.py` around line 1598) falls back to that ambient value
  whenever `info` isn't explicitly passed as a kwarg:
  ```python
  if info is None and "graphql_info" in self.context:
      info = self.context["graphql_info"]
  ```
  So omitting `info=` at the call site is a no-op once the middleware has already stashed
  it in `db.context`.

We also tried explicitly clearing `db.context.pop("graphql_info", None)` inside the
resolver right before calling `find_one`, to force a real opt-out. This avoids the crash,
but **corrupts the response** instead:
- The response comes back keyed by the raw view/table name (e.g.
  `tv_machine_inventory_statistics`) instead of the GraphQL field name
  (`machineInventoryStatistics`), because `field_name` resolution
  (`field_name = info.field_name` inside `find_one`) also depends on that same `info`.
- The multi-field case then fails with a *different* error:
  `ValueError: [TypeError("'RustResponseBytes' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]`
  — likely because `include_wrapper` (`not info.context.get("__has_multiple_root_fields__", False)`)
  also depends on the same ambient info and now always resolves to `True`, wrapping a
  result the multi-field merger expected unwrapped.

So as far as we can tell, there is **no fix available from resolver/application code** —
`field_name`, `include_wrapper`, and the field-path/selection-tree projection logic that
crashes are all coupled to the same single ambient `info` value, and there's no
documented way to independently control them.

## Impact

Any query combining 2+ top-level fields where at least one goes through
`db.find_one(...)` is at risk. In a real app this is an extremely common pattern (a
dashboard loading several counters/objects in one request), so this can silently take
down combined queries while each field individually appears to work fine in isolation —
which is exactly what happened to us (reported as a narrower, seemingly resolver-specific
bug before we found the real trigger).

## Environment

- `fraiseql==1.23.11` (`>=1.22,<2` line)
- Python 3.13
- PostgreSQL, `psycopg` (v3)

Happy to share a minimal standalone repro project if useful — the two examples above
were reduced from our production schema and reproduce with a bare `machineInventoryStatistics`/`me`-style
object query alongside any sibling field.

**Comment by evoludigit** [comment]
Fixed in #459 (merged to `dev`, squash `ba286caf`). Thanks for the unusually thorough report — the two-layer instinct was right, though the root cause of the second layer turned out different from the psycopg `UUIDDumper` guess.

**Bug A — `'dict' object has no attribute 'bytes'`** (the field that nulls out). Not psycopg. `find_one()` computes `include_wrapper = not context["__has_multiple_root_fields__"]`, so in **any** multi-field query it runs in field-only mode and `execute_via_rust_pipeline` returns a plain `dict`/`list` (not `RustResponseBytes`). `find_one()` then unconditionally called `_is_rust_response_null(result)`, which reads `result.bytes` — valid only on `RustResponseBytes`. That is the `'dict' object has no attribute 'bytes'`. Fix: guard the null-check by result type; in field-only mode the null sentinel is the empty list `[]`.

**Bug B — `TypeError: 'int' object is not an instance of 'str'`** (aborts the whole merge). A scalar sibling (e.g. `machinesCount` → `int`) produced `json_rows=[<int>]`, which the Rust FFI (`Vec<String>`) rejects at argument-extraction time, killing the entire merge and forcing the graphql-core fallback — where Bug A fires again. Fix: JSON-encode scalar/dict rows; non-JSON-native rows (typed objects, `RustResponseBytes`) still pass through raw so they fall back to graphql-core.

Your analysis of *why* application-side workarounds didn't help (the ambient `info` coupling `field_name` / `include_wrapper` / projection) was spot on — none of it was reachable from resolver code.

Coverage gap that let this ship: no multi-field test returned a bare scalar top-level field, and none exercised a real `db.find_one()` in field-only mode. Both paths now have unit + PostgreSQL integration regression tests.

One related follow-up opened: #460 — JSONB-derived **sub-fields** (e.g. a field from `data->>'x'`) can be dropped from a `find_one()`-backed object in multi-field queries (silently, no error). That's separate from this crash and does not block the fix, but it likely affects `machineInventoryStatistics { nMachine ... }`-style selections, so worth tracking. If you can confirm whether your combined queries now return complete objects (all sub-fields) once this ships, that data point would help prioritise #460.
